
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int GTEQ = 29;
  public static final int MULT = 40;
  public static final int LTEQ = 28;
  public static final int TFLOAT = 4;
  public static final int LPAREN = 15;
  public static final int CONTINUE = 8;
  public static final int FOR = 10;
  public static final int MINUS = 34;
  public static final int RPAREN = 16;
  public static final int OROR = 32;
  public static final int NOT = 26;
  public static final int SEMICOLON = 21;
  public static final int LT = 25;
  public static final int COMMA = 22;
  public static final int TBOOL = 2;
  public static final int CLASS = 7;
  public static final int DIV = 39;
  public static final int ANDAND = 31;
  public static final int PLUSEQ = 36;
  public static final int MINUSEQ = 37;
  public static final int EXTERN = 14;
  public static final int PLUS = 33;
  public static final int IF = 11;
  public static final int ID = 44;
  public static final int DOT = 38;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int error = 1;
  public static final int EQEQ = 27;
  public static final int MOD = 35;
  public static final int BREAK = 6;
  public static final int EQ = 23;
  public static final int TVOID = 5;
  public static final int LBRACK = 19;
  public static final int LBRACE = 17;
  public static final int ELSE = 9;
  public static final int TINTEGER = 3;
  public static final int RBRACK = 20;
  public static final int WHILE = 13;
  public static final int RBRACE = 18;
  public static final int FLOAT_LITERAL = 42;
  public static final int GT = 24;
  public static final int BOOL_LITERAL = 43;
  public static final int INT_LITERAL = 41;
  public static final int NOTEQ = 30;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TBOOL",
  "TINTEGER",
  "TFLOAT",
  "TVOID",
  "BREAK",
  "CLASS",
  "CONTINUE",
  "ELSE",
  "FOR",
  "IF",
  "RETURN",
  "WHILE",
  "EXTERN",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "LBRACK",
  "RBRACK",
  "SEMICOLON",
  "COMMA",
  "EQ",
  "GT",
  "LT",
  "NOT",
  "EQEQ",
  "LTEQ",
  "GTEQ",
  "NOTEQ",
  "ANDAND",
  "OROR",
  "PLUS",
  "MINUS",
  "MOD",
  "PLUSEQ",
  "MINUSEQ",
  "DOT",
  "DIV",
  "MULT",
  "INT_LITERAL",
  "FLOAT_LITERAL",
  "BOOL_LITERAL",
  "ID"
  };
}

